'=====================================…
Set WshShell = WScript.CreateObject("WScript.Shell")
obj = WshShell.Run("C:\dev\andersonbd1\home\scripts\message.bat", 0)
set WshShell = Nothing
'=====================================…
